Data import

In [1]:
import pandas as pd

In [2]:
Sales           = pd.read_csv('CSVDATA/True sales.csv')
Purchase        = pd.read_csv('CSVDATA/PurchasesFINAL12312016.csv')

Sales table optimisation

In [3]:
Sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 12825363 entries, 0 to 12825362
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     str
 1   Store           int64
 2   Brand           int64
 3   Description     str
 4   Size            str
 5   SalesQuantity   int64
 6   SalesDollars    float64
 7   SalesPrice      float64
 8   SalesDate       str
 9   Volume          float64
 10  Classification  int64
 11  ExciseTax       float64
 12  VendorNo        int64
 13  VendorName      str
dtypes: float64(4), int64(5), str(5)
memory usage: 2.3 GB

In [4]:
Sales_MinMax = Sales.agg(['min', 'max','dtype']).T
Sales_MinMax

,min,max,dtype
InventoryId,10_HORNSEY_1000,9_BLACKPOOL_999,str
Store,1,81,int64
Brand,58,90631,int64
Description,(RI) 1,von Buhl Jazz Rsl,str
Size,1.5L,Liter,str
SalesQuantity,1,1231,int64
SalesDollars,0.0,26061.14,float64
SalesPrice,0.0,5799.99,float64
SalesDate,2016-01-01,2016-12-31,str
Volume,50.0,20000.0,float64
Classification,1,2,int64
ExciseTax,0.01,1260.52,float64
VendorNo,2,201359,int64
VendorName,ADAMBA IMPORTS INTL INC,ZORVINO VINEYARDS,str

In [5]:
type_map = {
    'InventoryId'       :'category',
    'Store'             :'int8',
    'Brand'             :'int32',
    'Description'       :'category',
    'Size'              :'category',
    'SalesQuantity'     :'int16',
    'SalesDollars'      :'float16', # i dont recommend float 16 but its at least safe for this analysis
    'SalesPrice'        :'float16', 
    'Volume'            :'int16',
    'Classification'    :'int8'  , 
    'ExciseTax'         :'float16',
    'VendorNo'          :'int32',
    'VendorName'        :'category'
}

Sales = Sales.astype(type_map)

In [6]:
Sales['SalesDate']= pd.to_datetime(Sales['SalesDate']).dt.normalize()

In [7]:
Sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 12825363 entries, 0 to 12825362
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     category
 1   Store           int8
 2   Brand           int32
 3   Description     category
 4   Size            category
 5   SalesQuantity   int16
 6   SalesDollars    float16
 7   SalesPrice      float16
 8   SalesDate       datetime64[us]
 9   Volume          int16
 10  Classification  int8
 11  ExciseTax       float16
 12  VendorNo        int32
 13  VendorName      category
dtypes: category(4), datetime64[us](1), float16(3), int16(2), int32(2), int8(2)
memory usage: 459.3 MB

Purchase data optimisation

In [8]:
Purchase.info()

<class 'pandas.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 16 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     str
 1   Store           int64
 2   Brand           int64
 3   Description     str
 4   Size            str
 5   VendorNumber    int64
 6   VendorName      str
 7   PONumber        int64
 8   PODate          str
 9   ReceivingDate   str
 10  InvoiceDate     str
 11  PayDate         str
 12  PurchasePrice   float64
 13  Quantity        int64
 14  Dollars         float64
 15  Classification  int64
dtypes: float64(2), int64(6), str(8)
memory usage: 537.1 MB

In [9]:
Purchase.nunique()

InventoryId       245907
Store                 80
Brand              10664
Description         9652
Size                  51
VendorNumber         126
VendorName           129
PONumber            5543
PODate               319
ReceivingDate        364
InvoiceDate          373
PayDate              382
PurchasePrice       2151
Quantity             686
Dollars            33567
Classification         2
dtype: int64

In [10]:
Purchase_MinMax = Purchase.agg(['min' , 'max','dtype']).T
Purchase_MinMax

,min,max,dtype
InventoryId,10_HORNSEY_1001,9_BLACKPOOL_999,str
Store,1,81,int64
Brand,58,90631,int64
Description,(RI) 1,von Buhl Jazz Rsl,str
Size,1.5L,Liter,str
VendorNumber,2,201359,int64
VendorName,AAPER ALCOHOL & CHEMICAL CO,ZORVINO VINEYARDS,str
PONumber,8106,13661,int64
PODate,2015-12-20,2016-12-23,str
ReceivingDate,2016-01-01,2016-12-31,str
InvoiceDate,2016-01-04,2017-01-10,str
PayDate,2016-02-04,2017-02-19,str
PurchasePrice,0.0,5681.81,float64
Quantity,1,3816,int64
Dollars,0.0,50175.7,float64
Classification,1,2,int64

In [11]:
dtype_map = {
    'InventoryId'   :'category',
    'Store'         :'int8',
    'Brand'         :'int32',
    'Description'   :'category',
    'Size'          :'category',
    'VendorNumber'  :'int32',
    'VendorName'    :'category',
    'PONumber'      :'int16',
    'PurchasePrice' :'float16',
    'Quantity'      :'int16',
    'Dollars'       :'float32',
    'Classification':'int8'	
}
Purchase=Purchase.astype(dtype_map)

In [12]:
Purchase[['PODate','ReceivingDate','InvoiceDate','PayDate']]=Purchase[['PODate','ReceivingDate','InvoiceDate','PayDate']].apply(pd.to_datetime).apply(lambda x : x.dt.normalize())

In [13]:
Purchase.info()

<class 'pandas.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 16 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     category
 1   Store           int8
 2   Brand           int32
 3   Description     category
 4   Size            category
 5   VendorNumber    int32
 6   VendorName      category
 7   PONumber        int16
 8   PODate          datetime64[us]
 9   ReceivingDate   datetime64[us]
 10  InvoiceDate     datetime64[us]
 11  PayDate         datetime64[us]
 12  PurchasePrice   float16
 13  Quantity        int16
 14  Dollars         float32
 15  Classification  int8
dtypes: category(4), datetime64[us](4), float16(1), float32(1), int16(2), int32(2), int8(2)
memory usage: 144.2 MB

In [16]:
Sales.to_parquet('Sales.praquet',index=False)
Purchase.to_parquet('Purchase.praquet' ,index=False)