Data import

In [1]:
import pandas as pd

In [2]:
Sales           = pd.read_csv('CSVDATA/SalesFINAL12312016.csv')
Future_Price    = pd.read_csv('CSVDATA/2017PurchasePricesDec.csv')
Purchase        = pd.read_csv('CSVDATA/PurchasesFINAL12312016.csv')
Purchase_invoice= pd.read_csv('CSVDATA/InvoicePurchases12312016.csv')
Invoice_Begin   = pd.read_csv('CSVDATA/BegInvFINAL12312016.csv')
Invoice_End     = pd.read_csv('CSVDATA/EndInvFINAL12312016.csv')

Sales table optimisation

In [3]:
Sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 14 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   InventoryId     1048575 non-null  str
 1   Store           1048575 non-null  int64
 2   Brand           1048575 non-null  int64
 3   Description     1048575 non-null  str
 4   Size            1048575 non-null  str
 5   SalesQuantity   1048575 non-null  int64
 6   SalesDollars    1048575 non-null  float64
 7   SalesPrice      1048575 non-null  float64
 8   SalesDate       1048575 non-null  str
 9   Volume          1048575 non-null  int64
 10  Classification  1048575 non-null  int64
 11  ExciseTax       1048575 non-null  float64
 12  VendorNo        1048575 non-null  int64
 13  VendorName      1048575 non-null  str
dtypes: float64(3), int64(6), str(5)
memory usage: 190.0 MB

In [4]:
Sales.isnull().sum()

InventoryId       0
Store             0
Brand             0
Description       0
Size              0
SalesQuantity     0
SalesDollars      0
SalesPrice        0
SalesDate         0
Volume            0
Classification    0
ExciseTax         0
VendorNo          0
VendorName        0
dtype: int64

In [5]:
Sales_MinMax = Sales.agg(['min', 'max','dtype']).T
Sales_MinMax

,min,max,dtype
InventoryId,10_HORNSEY_1000,9_BLACKPOOL_984,str
Store,1,79,int64
Brand,58,90089,int64
Description,(RI) 1,von Buhl Jazz Rsl,str
Size,1.5L,Liter,str
SalesQuantity,1,432,int64
SalesDollars,0.49,13279.97,float64
SalesPrice,0.49,4999.99,float64
SalesDate,1/1/2016,2/9/2016,str
Volume,50,20000,int64
Classification,1,2,int64
ExciseTax,0.01,378.52,float64
VendorNo,2,173357,int64
VendorName,ALISA CARR BEVERAGES,ZORVINO VINEYARDS,str

In [6]:
type_map = {
    'InventoryId'       :'category',
    'Store'             :'int8',
    'Brand'             :'int32',
    'Description'       :'category',
    'Size'              :'category',
    'SalesQuantity'     :'int16',
    'SalesDollars'      :'float32',
    'SalesPrice'        :'float32', 
    'Volume'            :'int32',
    'Classification'    :'int8'  , 
    'ExciseTax'         :'float32',
    'VendorNo'          :'int32',
    'VendorName'        :'category'
}

Sales = Sales.astype(type_map)

In [7]:
Sales['SalesDate']= pd.to_datetime(Sales['SalesDate']).dt.normalize()

In [8]:
Sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 14 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   InventoryId     1048575 non-null  category
 1   Store           1048575 non-null  int8
 2   Brand           1048575 non-null  int32
 3   Description     1048575 non-null  category
 4   Size            1048575 non-null  category
 5   SalesQuantity   1048575 non-null  int16
 6   SalesDollars    1048575 non-null  float32
 7   SalesPrice      1048575 non-null  float32
 8   SalesDate       1048575 non-null  datetime64[us]
 9   Volume          1048575 non-null  int32
 10  Classification  1048575 non-null  int8
 11  ExciseTax       1048575 non-null  float32
 12  VendorNo        1048575 non-null  int32
 13  VendorName      1048575 non-null  category
dtypes: category(4), datetime64[us](1), float32(3), int16(1), int32(3), int8(2)
memory usage: 48.3 MB

Purchase data optimisation

In [9]:
Purchase.info()

<class 'pandas.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 16 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     str
 1   Store           int64
 2   Brand           int64
 3   Description     str
 4   Size            str
 5   VendorNumber    int64
 6   VendorName      str
 7   PONumber        int64
 8   PODate          str
 9   ReceivingDate   str
 10  InvoiceDate     str
 11  PayDate         str
 12  PurchasePrice   float64
 13  Quantity        int64
 14  Dollars         float64
 15  Classification  int64
dtypes: float64(2), int64(6), str(8)
memory usage: 537.1 MB

In [10]:
Purchase.nunique()

InventoryId       245907
Store                 80
Brand              10664
Description         9652
Size                  51
VendorNumber         126
VendorName           129
PONumber            5543
PODate               319
ReceivingDate        364
InvoiceDate          373
PayDate              382
PurchasePrice       2151
Quantity             686
Dollars            33567
Classification         2
dtype: int64

In [11]:
Purchase_MinMax = Purchase.agg(['min' , 'max','dtype']).T
Purchase_MinMax

,min,max,dtype
InventoryId,10_HORNSEY_1001,9_BLACKPOOL_999,str
Store,1,81,int64
Brand,58,90631,int64
Description,(RI) 1,von Buhl Jazz Rsl,str
Size,1.5L,Liter,str
VendorNumber,2,201359,int64
VendorName,AAPER ALCOHOL & CHEMICAL CO,ZORVINO VINEYARDS,str
PONumber,8106,13661,int64
PODate,2015-12-20,2016-12-23,str
ReceivingDate,2016-01-01,2016-12-31,str
InvoiceDate,2016-01-04,2017-01-10,str
PayDate,2016-02-04,2017-02-19,str
PurchasePrice,0.0,5681.81,float64
Quantity,1,3816,int64
Dollars,0.0,50175.7,float64
Classification,1,2,int64

In [12]:
dtype_map = {
    'InventoryId'   :'category',
    'Store'         :'int8',
    'Brand'         :'int32',
    'Description'   :'category',
    'Size'          :'category',
    'VendorNumber'  :'int32',
    'VendorName'    :'category',
    'PONumber'      :'int16',
    'PurchasePrice' :'float16',
    'Quantity'      :'int16',
    'Dollars'       :'float32',
    'Classification':'int8'	
}
Purchase=Purchase.astype(dtype_map)

In [13]:
Purchase[['PODate','ReceivingDate','InvoiceDate','PayDate']]=Purchase[['PODate','ReceivingDate','InvoiceDate','PayDate']].apply(pd.to_datetime).apply(lambda x : x.dt.normalize())

In [14]:
Purchase.info()

<class 'pandas.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 16 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     category
 1   Store           int8
 2   Brand           int32
 3   Description     category
 4   Size            category
 5   VendorNumber    int32
 6   VendorName      category
 7   PONumber        int16
 8   PODate          datetime64[us]
 9   ReceivingDate   datetime64[us]
 10  InvoiceDate     datetime64[us]
 11  PayDate         datetime64[us]
 12  PurchasePrice   float16
 13  Quantity        int16
 14  Dollars         float32
 15  Classification  int8
dtypes: category(4), datetime64[us](4), float16(1), float32(1), int16(2), int32(2), int8(2)
memory usage: 144.2 MB

Changing Date Dtypes

In [15]:
Invoice_Begin['startDate']  = pd.to_datetime(Invoice_Begin['startDate']).dt.normalize()
Invoice_End['endDate']      = pd.to_datetime(Invoice_End['endDate']).dt.normalize()
Purchase_invoice[['InvoiceDate','PODate','PayDate']]=Purchase_invoice[['InvoiceDate','PODate','PayDate']].apply(pd.to_datetime).apply(lambda x: x.dt.normalize())

ABC analysis

Store Competitiveness

In [16]:
S_Competitive= Sales.groupby('Store').sum(numeric_only=True).sort_values(by=['SalesDollars','SalesQuantity'],ascending=[False,False])[['SalesQuantity','SalesDollars']]

In [17]:
S_Competitive['percentage']       = (S_Competitive['SalesDollars']/S_Competitive['SalesDollars'].sum())*100
S_Competitive['percentage_Cumul'] = S_Competitive['percentage'].cumsum()
S_Competitive['count']            = range(1,len(S_Competitive)+1)
S_Competitive['Count_percentage'] = (S_Competitive['count']/S_Competitive['count'].max())*100
S_Competitive['ABC Count']        = S_Competitive['Count_percentage'].apply(lambda x :'A' if x <= 20 else ('B' if x <=50 else 'C') )
S_Competitive['ABC Sales']        = S_Competitive['percentage_Cumul'].apply(lambda x :'A' if x <= 80 else ('B' if x <=95 else 'C') )
S_Competitive['ABC_Matrix']       = S_Competitive['ABC Count'] + S_Competitive['ABC Sales']

In [18]:
S_Competitive.reset_index(inplace=True)

Products Competitiveness (company overall)

In [19]:
brand_class                     = pd.DataFrame([])
brand_class['Brand']            = Sales['Brand'].unique()
brand_class['Classification']   = Sales[Sales['Brand'].isin(brand_class['Brand'])]['Classification']

In [20]:
Company_ABC = Sales.groupby('Brand').sum(numeric_only=True).sort_values(by=['SalesDollars','SalesQuantity'],ascending=[False,False])[['SalesQuantity','SalesDollars']]

In [21]:
Company_ABC.reset_index(inplace=True)


Company_ABC

      Brand  SalesQuantity  SalesDollars
0      4261          20226  444810.75000
1      3545          11883  357759.15625
2      1233           9578  344712.21875
3      8068          11189  288135.09375
4      3405           9203  275162.96875
...     ...            ...           ...
7653   8729              2       1.98000
7654   2773              1       0.99000
7655   3303              1       0.99000
7656   8872              1       0.99000
7657   5287              2       0.98000

[7658 rows x 3 columns]

In [22]:
Company_ABC['Classification']= brand_class[Company_ABC['Brand'].isin(brand_class['Brand'])]['Classification'] 
Company_ABC = Company_ABC[['Brand','Classification','SalesQuantity','SalesDollars']]

In [23]:
Company_ABC['percentage']       = (Company_ABC['SalesDollars']/Company_ABC['SalesDollars'].sum())*100
Company_ABC['percentage_Cumul'] = Company_ABC['percentage'].cumsum()
Company_ABC['count']            = range(1,len(Company_ABC)+1)
Company_ABC['Count_percentage'] = (Company_ABC['count']/Company_ABC['count'].max())*100
Company_ABC['ABC Count']        = Company_ABC['Count_percentage'].apply(lambda x :'A' if x <= 20 else ('B' if x <=50 else 'C') )
Company_ABC['ABC Sales']        = Company_ABC['percentage_Cumul'].apply(lambda x :'A' if x <= 80 else ('B' if x <=95 else 'C') )
Company_ABC['ABC_Matrix']       = Company_ABC['ABC Count'] + Company_ABC['ABC Sales']

Making company overall based on product classification

In [24]:
Company_ABC_one = Company_ABC[Company_ABC['Classification']== 1]
Company_ABC_one['percentage']       = (Company_ABC_one['SalesDollars']/Company_ABC_one['SalesDollars'].sum())*100
Company_ABC_one['percentage_Cumul'] = Company_ABC_one['percentage'].cumsum()
Company_ABC_one['count']            = range(1,len(Company_ABC_one)+1)
Company_ABC_one['Count_percentage'] = (Company_ABC_one['count']/Company_ABC_one['count'].max())*100
Company_ABC_one['ABC Count']        = Company_ABC_one['Count_percentage'].apply(lambda x :'A' if x <= 20 else ('B' if x <=50 else 'C') )
Company_ABC_one['ABC Sales']        = Company_ABC_one['percentage_Cumul'].apply(lambda x :'A' if x <= 80 else ('B' if x <=95 else 'C') )
Company_ABC_one['ABC_Matrix']       = Company_ABC_one['ABC Count'] + Company_ABC_one['ABC Sales']

In [25]:
Company_ABC_Two = Company_ABC[Company_ABC['Classification']== 2]
Company_ABC_Two['percentage']       = (Company_ABC_Two['SalesDollars']/Company_ABC_Two['SalesDollars'].sum())*100
Company_ABC_Two['percentage_Cumul'] = Company_ABC_Two['percentage'].cumsum()
Company_ABC_Two['count']            = range(1,len(Company_ABC_Two)+1)
Company_ABC_Two['Count_percentage'] = (Company_ABC_Two['count']/Company_ABC_Two['count'].max())*100
Company_ABC_Two['ABC Count']        = Company_ABC_Two['Count_percentage'].apply(lambda x :'A' if x <= 20 else ('B' if x <=50 else 'C') )
Company_ABC_Two['ABC Sales']        = Company_ABC_Two['percentage_Cumul'].apply(lambda x :'A' if x <= 80 else ('B' if x <=95 else 'C') )
Company_ABC_Two['ABC_Matrix']       = Company_ABC_Two['ABC Count'] + Company_ABC_Two['ABC Sales']

Stores Best selling products (ABC)

In [26]:
Sales.head()

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.490000,16.490000,2016-01-01,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.980000,16.490000,2016-01-02,750,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.490000,16.490000,2016-01-03,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.490000,14.490000,2016-01-08,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.980003,34.990002,2016-01-09,375,1,0.79,12546,JIM BEAM BRANDS COMPANY

In [27]:
Store_ABC = pd.DataFrame([])
Store_ABC = Sales.groupby(by=['Store','Brand']).sum(numeric_only=True)[['SalesQuantity','SalesDollars']].reset_index()

In [28]:
Store_ABC.sort_values(by=['Store','SalesDollars','SalesQuantity'],ascending=[True,False,False],inplace=True)
Store_ABC.reset_index(drop=True,inplace=True)

In [29]:
Store_ABC['SumSalesByStore'] = Store_ABC.groupby(by='Store')['SalesDollars'].transform('sum')

In [30]:
Store_ABC['percentage'] = (Store_ABC['SalesDollars']/Store_ABC['SumSalesByStore'])*100

In [31]:
Store_ABC['percentage_Cumul'] = Store_ABC.groupby(by='Store')['percentage'].cumsum()

In [32]:
Store_ABC['ABC'] = Store_ABC['percentage_Cumul'].apply(lambda x :'A' if x <= 20 else ('B' if x <=50 else 'C'))